---
- name: Remove old package
  shell: sudo apt remove tr-archive -y
  ignore_errors: true

- name: Install deb package full
  shell: apt install "{{ home_dir }}/deployment/{{ DEB_NAME }}" -y 
  
- name: Remove deb-package
  shell: rm -rf "./{{ DEB_NAME }}"

- name: Set privilleges tr-archive
  shell: chown -R www-data:www-data /var/www/tr-archive/