---
- name: Copy backend sources 
  copy:
    src: "{{ home_dir }}/sources/tr-archive-back-5.3.0-trch.zip"
    dest: {{ home_dir }}

- name: Copy frontend sources 
  copy:
    src: "{{ home_dir }}/sources/tr-archive-v-5.3.0-trch.zip"
    dest: {{ home_dir }}
    
- name: Copy public API sources 
  copy:
    src: "{{ home_dir }}/sources/tr-archive-public-proxy-api-1.3.1-intgapi.zip"
    dest: {{ home_dir }}

- name: Copy notification sources 
  copy:
    src: "{{ home_dir }}/sources/tr-archive-notification-3.3.0-trch.zip"
    dest: {{ home_dir }}

- name: Copy workers sources 
  copy:
    src: "{{ home_dir }}/sources/tr-archive-worker-5.2.0-trch.zip"
    dest: {{ home_dir }}

- name: Create deb-package directory
  shell: mkdir {{ home_dir }}/deploy/tr-archive-deb-package

- name: Unzip backend directory
  unarchive:
    src: "{{ home_dir }}/{{ back_arch }}"
    dest: "{{ home_dir }}/deploy/tr-archive-deb-package"
  become: true

- name: Unzip frontend directory
  unarchive:
    src: "{{ home_dir }}/{{ front_arch }}"
    dest: "{{ home_dir }}/deploy/tr-archive-deb-package"                
  become: true

- name: Unzip notification directory
  unarchive:
    src: "{{ home_dir }}/{{ notif_arch }}"
    dest: "{{ home_dir }}/deploy/tr-archive-deb-package"                
  become: true

- name: Unzip worker directory
  unarchive:
    src: "{{ home_dir }}/{{ worker_arch }}"
    dest: "{{ home_dir }}/deploy/tr-archive-deb-package"                
  become: true

- name: Unzip public API directory
  unarchive:
    src: "{{ home_dir }}/{{ public_arch }}"
    dest: "{{ home_dir }}/deploy/tr-archive-deb-package"                
  become: true

- name: "rename backend dir"
  shell: cd {{ home_dir }}/deploy/tr-archive-deb-package && mv tr-archive-back-master tr-archive-back       
  ignore_errors: yes

- name: "rename frontend dir"
  shell: cd {{ home_dir }}/deploy/tr-archive-deb-package && mv tr-archive-v-master tr-archive-v   
  ignore_errors: yes

- name: "rename notification dir"
  shell: cd {{ home_dir }}/deploy/tr-archive-deb-package && mv tr-archive-notification-master tr-archive-notification
  ignore_errors: yes

- name: "rename worker dir"
  shell: cd {{ home_dir }}/deploy/tr-archive-deb-package && mv tr-archive-worker-master tr-archive-worker
  ignore_errors: yes

- name: "composer install backend"
  shell: cd {{ home_dir }}/deploy/tr-archive-deb-package/tr-archive-back && composer install

- name: "composer install public API"
  shell: cd {{ home_dir }}/deploy/tr-archive-deb-package/trarchivepublic && composer install

- name: "compose install notification"
  shell: cd {{ home_dir }}/deploy/tr-archive-deb-package/tr-archive-notification && composer install

- name: "npm install and build frontend"
  shell: cd {{ home_dir }}/deploy/tr-archive-deb-package/tr-archive-v && npm install && npm run build-v-dev

- name: "build deb package"
  shell: |
    cp -r {{ home_dir }}/deploy/debinstall {{ home_dir }}/deploy/tr-archive-deb-package/
    cd {{ home_dir }}/deploy/tr-archive-deb-package/debinstall && ./redeb.sh 

- name: "replace deb package to ansible workdir"
  shell: mv {{ home_dir }}/deploy/tr-archive-deb-package/debinstall/tr-archive.deb {{ home_dir }}/deploy/

- name: "remove tmp debinstall directory"
  shell: rm -rf {{ home_dir }}/deploy/tr-archive-deb-package/debinstall
